---
title: "phylogeny S aureus and C jejuni"
author: "Joao Carlos Gomes-Neto"
date: "8/15/2020"
output: html_document
---

Loading the necessary packages 
```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(Rtsne)

# Install ggtree 
#if (!requireNamespace("BiocManager", quietly = TRUE))
  # install.packages("BiocManager")
#BiocManager::install(version = "3.11")

#BiocManager::install("ggtree")

# Load ggtree

library(ggtree)
```

Plot A. C. jejuni plot (phylogeny, ST, and BAPS1)

```{r, include = FALSE}

# Enter the phylogeny for Typhimurium group1

tree_group_1 <- read.tree("jejuni_phylogeny_gr1.tree")

#############################################

# Enter Baps 1-6 for group1

baps_group_1 <- read_csv('output.roary_output_95_95_1.fastbaps_level_6.csv')

# Changing column names 

colnames(baps_group_1)[1:2] <- c("id", "baps_1") 

# Select colunms id and baps_1
b1 <- baps_group_1 %>% 
              select(id, baps_1)

# QC the data

skim(b1)

###########################################

# Enter MLST results

mlst <- read_csv('mlst_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

# QC the data

skim(s1)

#####################################################################

# Merge BAPS, MLST and SISTR results 

## Merge baps and mslt first

d1 <- left_join(b1, s1, on = "id") # merge mlst and baps

# st

d1$st <- ifelse(d1$ST == 353, "ST353", 
                ifelse(d1$ST == 45, "ST45",
                ifelse(d1$ST == 982, "ST982",
                ifelse(d1$ST == 48, "ST48",
                ifelse(d1$ST == 50, "ST50",
                ifelse(d1$ST == 8, "ST8",
                ifelse(d1$ST == 806, "ST806",
                ifelse(d1$ST == 459, "ST459",
                       "Other STs"))))))))
                       
# baps

d1$baps1 <- ifelse(d1$baps_1 == 13, "13", 
                   ifelse(d1$baps_1 == 14, "14", 
                          ifelse(d1$baps_1 == 16, "16", 
                                 ifelse(d1$baps_1 == 19, "19", 
                                        ifelse(d1$baps_1 == 22, "22", 
                                               ifelse(d1$baps_1 == 24, "24", 
                       "Other sub-groups"))))))

# Replace NA in the ST column

d1 <- d1 %>% mutate(st = replace_na(st, "Other STs"))
d1 <- d1 %>% mutate(baps1 = replace_na(baps1, "Other sub-groups"))

table(d1$st)
table(d1$baps_1)

########################################################################

# Plot the phylogeny

# Select the columns needed from d2

d2 <- d1 %>% 
                    select("id", "baps1", "st") 

# Make id the rowname or index

d2 <- column_to_rownames(d2, var = "id") 

# Create the tree

t1 <- ggtree(tree_group_1, layout = "circular") + xlim(-50, NA)


fig7a <- gheatmap(t1, d2, offset=.0, width=10, colnames = FALSE) +
  scale_fill_manual(values = c("gray", "darkblue",
                               "cornflowerblue", "coral", "darkgreen", "red",
                                 "darkseagreen3", "darkcyan", "darksalmon",
                               "brown", "black", "darkblue", "purple", 
                               "orange", "red", "gray"),
                    breaks = c("13", "14", "16", "19", "22", "24", "Other sub-groups",
                               "ST8", "ST45", "ST48", "ST50", "ST353", "ST459", 
                               "ST806", "ST982", "Other STs"),
                    name= "BAPS1 (innermost) -> ST (outermost)") +
  ggtitle(expression(bold(paste("A. Hierarchical population structure - ", bolditalic(C),". ", bolditalic(jejuni))))) +
  theme(plot.title = element_text(size = 40, face = "bold"), 
        legend.title=element_text(size=24, face = "bold"), 
    legend.text=element_text(size=22))
fig7a
```

Plot B. S. aureus plot (phylogeny, ST, and BAPS1)

```{r, include = FALSE}

# Enter the phylogeny for Typhimurium group1

tree_group_1 <- read.tree("saureus_phylogeny_gr1.tree")

#############################################

# Enter Baps 1-6 for group1

baps_group_1 <- read_csv('output.roary_output_1.fastbaps_level_6.csv')

# Changing column names 

colnames(baps_group_1)[1:2] <- c("id", "baps_1") 

# Select colunms id and baps_1
b1 <- baps_group_1 %>% 
              select(id, baps_1)

# QC the data

skim(b1)

###########################################

# Enter MLST results

mlst <- read_csv('saureus_st.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'/'), "[", 8)
mlst <- mlst %>% separate(id2, c("id", "day"), sep = "\\.")

# Select columns of interest

s1 <- mlst %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

# QC the data

skim(s1)

#####################################################################

# Merge BAPS, MLST and SISTR results 

## Merge baps and mslt first

d1 <- left_join(b1, s1, on = "id") # merge mlst and baps

# st

d1$st <- ifelse(d1$ST == 8, "ST8", 
                ifelse(d1$ST == 5, "ST5",
                ifelse(d1$ST == 105, "ST105",
                ifelse(d1$ST == 398, "ST398",
                ifelse(d1$ST == 609, "ST609",
                ifelse(d1$ST == 45, "ST45",
                       "Other STs"))))))
                       
# Replace NA in the ST column

d1 <- d1 %>% mutate(st = replace_na(st, "Other STs"))

table(d1$st)
table(d1$baps_1)

########################################################################

# Plot the phylogeny

# Select the columns needed from d2

d2 <- d1 %>% 
                    select("id", "baps_1", "st") %>%
                    mutate(baps_1 = as.factor(baps_1))

# Make id the rowname or index

d2 <- column_to_rownames(d2, var = "id") 

# Create the tree

t1 <- ggtree(tree_group_1, layout = "circular") + xlim(-50, NA)


fig7b <- gheatmap(t1, d2, offset=.0, width=150, colnames = FALSE) +
  scale_fill_manual(values = c("gray", "darkblue",
                               "cornflowerblue", "coral", "darkgreen", "red",
                                 "darkseagreen3", "darkcyan", "gray",
                               "brown", "black", "darkblue", "purple", 
                               "orange"),
                    breaks = c("1", "2", "3", "4", "5", "6", "7",
                               "ST5", "ST8", "ST45", "ST105", "ST398", "ST609", 
                               "Other STs"),
                    name= "BAPS1 (innermost) -> ST (outermost)") +
  ggtitle(expression(bold(paste("B. Hierarchical population structure - ", bolditalic(S),". ", bolditalic(aureus))))) +
  theme(plot.title = element_text(size = 40, face = "bold"), 
        legend.title=element_text(size=24, face = "bold"), 
    legend.text=element_text(size=22))
fig7b
```
