---
title: "Salmonella antibiotic resistance"
author: "Joao Carlos Gomes-Neto"
date: "7/18/2020"
output: html_document
---

Load packages

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)    
library(factoextra) 
library(dendextend)

```

Salmonella Typhimurium

```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'/'), "[", 3)
s1 <- mlst %>% separate(id2, c("id", "day"), sep = "\\.")

# Select columns of interest

s2 <- s1 %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

# QC the data

skim(s2)

# st

s2$st <- ifelse(s2$ST == 19, "ST19", 
                   ifelse(s2$ST == 34, "ST34", 
                          ifelse(s2$ST == 36, "ST36",
                                 ifelse(s2$ST == 313, "ST313", "Other STs"))))

# Create data1 

data1 <- s2 
data1 <- data1 %>% select(-ST)
data1[is.na(data1)] <- "Other STs"

# Enter resfinder data

abx1 <- read_csv('sabricate_resfinder_output_typhimurium.csv')
abx1$serovar <- "Typhimurium"
abx1$id2 <- sapply(strsplit(as.character(abx1$'#FILE'),'/'), "[", 3)
abx2 <- abx1 %>% separate(id2, c("id", "day"), sep = "\\.")
abx2 <- abx2 %>% mutate(gene = GENE)
abx3 <- abx2 %>% select(id, gene, serovar)

# merge data

typabx <- left_join(data1, abx3, on =  "id")

# select columns that you need

typabx <- typabx %>% select(id, st, gene, serovar)

# select id, st, serovar

t1 <- typabx %>% select(id, gene, serovar)

# counts of genes by id

t2 <- typabx %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

t3 <- t2 %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = dim(data1)[1]) %>%
         mutate(prop = (value/total)*100)

t4 <- t3 %>% select(gene, prop)
t5 <- t4 %>% mutate(serovar = "Typhimurium")

# merge data

t6 <- t5 %>% drop_na() 
```

Salmonella Newport

```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id2, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                  rename(id = id2)

# st

s1$st <- ifelse(s1$ST == 5, "ST5", 
                   ifelse(s1$ST == 45, "ST45", 
                          ifelse(s1$ST == 118, "ST118", "Other STs")))

data1 <- s1
data1 <- data1 %>% select(-ST)
data1[is.na(data1)] <- "Other STs"

# Enter resfinder data

abx1 <- read_csv('sabricate_resfinder_output_newport.csv')
abx1$serovar <- "Newport"
abx1$id <- sapply(strsplit(as.character(abx1$'#FILE'),'_'), "[", 1)
abx1 <- abx1 %>% mutate(gene = GENE)
abx2 <- abx1 %>% select(id, gene, serovar)

# merge data

newabx <- left_join(data1, abx2, on =  "id")

# select columns that you need

newabx <- newabx %>% select(id, st, gene, serovar)

# select id, st, serovar

n1 <- newabx %>% select(id, gene, serovar)

# counts of genes by id

n2 <- newabx %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

n3 <- n2 %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = dim(data1)[1]) %>%
         mutate(prop = (value/total)*100)

n4 <- n3 %>% select(gene, prop)
n5 <- n4 %>% mutate(serovar = "Newport")

# merge data

n6 <- n5 %>% drop_na() 
```

Salmonella infantis


```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id2, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                  rename(id = id2)

# st

s1$st <- ifelse(s1$ST == 32, "ST32", "Other STs")

data1 <- s1
data1 <- data1 %>% select(-ST)
data1[is.na(data1)] <- "Other STs"

# Enter resfinder data

abx1 <- read_csv('sabricate_resfinder_output_infantis.csv')
abx1$serovar <- "Infantis"
abx1$id2 <- sapply(strsplit(as.character(abx1$'#FILE'),'/'), "[", 3)
abx2 <- abx1 %>% separate(id2, c("id", "day"), sep = "\\_")
abx2 <- abx2 %>% mutate(gene = GENE)
abx3 <- abx2 %>% select(id, gene, serovar)

# merge data

infabx <- left_join(data1, abx3, on =  "id")

# select columns that you need

infabx <- infabx %>% select(id, st, gene, serovar)

# select id, st, serovar

i1 <- infabx %>% select(id, gene, serovar)

# counts of genes by id

i2 <- infabx %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

i3 <- i2 %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = dim(data1)[1]) %>%
         mutate(prop = (value/total)*100)

i4 <- i3 %>% select(gene, prop)
i5 <- i4 %>% mutate(serovar = "Infantis")

# merge data

i6 <- i5 %>% drop_na() 
```

Combine all three datasets and plot resistance based on Serovar
```{r, include = FALSE}

dataAbx <- rbind(t6, n6, i6)

# Drop NA
d1 <- dataAbx %>% drop_na()

colors = c("")
d2 <- d1 %>% filter(prop >= 25)
p1 <- ggplot(data = d2, mapping = aes(x = prop, y=gene, fill = gene)) + 
      geom_bar(stat = "identity") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
      theme(axis.text.y = element_text(size = 25)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      theme(legend.position = "none") +
      ggtitle("A.      Serovars") +
      scale_fill_manual(values = c("darksalmon", "deeppink3", "azure4", "bisque", "darkslateblue", 
                                   "cyan", "orange", "beige", "purple", "brown",
                                   "grey", "darkgreen", "black", "blue", 
                                   "red"))+
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ serovar)
p1
```

Plot abx distribution within Infantis

```{r, include = FALSE}

# Drop NA
d1 <- infabx %>% drop_na()

# Get the number distinct STs

a <- d1 %>% select(id, st) %>% group_by(id)
b <- distinct(a, id, st)
table(b$st)

###############################################
# Calculations for Other STs 

d2a <- d1 %>% filter(st == "Other STs")

d3a <- d2a %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4a <- d3a %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 18) %>%
         mutate(prop = (value/total)*100)

d5a <- d4a %>% mutate(st = "Other STs")

###############################################
# Calculations for ST32

d2b <- d1 %>% filter(st == "ST32")

d3b <- d2b %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4b <- d3b %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 1666) %>%
         mutate(prop = (value/total)*100)

d5b <- d4b %>% mutate(st = "ST32")

# combined datasets

d6 <- rbind(d5a, d5b)

d7 <- d6 %>% filter(prop >= 25)
p2 <- ggplot(data = d7, mapping = aes(x = prop, y=gene, fill = gene)) + 
      geom_bar(stat = "identity") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      #xlim(0, 100) +
      theme(legend.position = "none") +
      scale_fill_manual(values = c("darksalmon", "deeppink3", "azure4", "darkslateblue", 
                                   "cyan", "beige", "brown",
                                   "grey", "darkgreen", "black", 
                                   "red"))+
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(axis.text.y = element_text(size = 35)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle(expression(bold(paste("B.      ", bolditalic(S), ". Infantis")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ st) 
p2
```

Plot abx distribution within Newport

```{r, include = FALSE}

# Drop NA
d1 <- newabx %>% drop_na()

# Get the number distinct STs

a <- d1 %>% select(id, st) %>% group_by(id)
b <- distinct(a, id, st)
table(b$st)

###############################################
# Calculations for Other STs 

d2a <- d1 %>% filter(st == "Other STs")

d3a <- d2a %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4a <- d3a %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 393) %>%
         mutate(prop = (value/total)*100)

d5a <- d4a %>% mutate(st = "Other STs")

###############################################
# Calculations for ST118

d2b <- d1 %>% filter(st == "ST118")

d3b <- d2b %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4b <- d3b %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 800) %>%
         mutate(prop = (value/total)*100)

d5b <- d4b %>% mutate(st = "ST118")

###############################################
# Calculations for ST45

d2c <- d1 %>% filter(st == "ST45")

d3c <- d2c %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4c <- d3c %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 643) %>%
         mutate(prop = (value/total)*100)

d5c <- d4c %>% mutate(st = "ST45")

###############################################
# Calculations for ST5

d2d <- d1 %>% filter(st == "ST5")

d3d <- d2d %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4d <- d3d %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 529) %>%
         mutate(prop = (value/total)*100)

d5d <- d4d %>% mutate(st = "ST5")

#################################################
# combined datasets

d6 <- rbind(d5a, d5b, d5c, d5d)

d7 <- d6 %>% filter(prop >= 25)
p3 <- ggplot(data = d7, mapping = aes(x = prop, y=gene, fill = gene)) + 
      geom_bar(stat = "identity") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      #xlim(0, 105) +
       theme(legend.position = "none") +
      scale_fill_manual(values = c("deeppink3", "bisque", "orange", 
                                   "darkred", "grey", "darkgreen",
                                   "cornsilk", 
                                   "red"))+
      theme(axis.text.y = element_text(size = 25)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle(expression(bold(paste("C.      ", bolditalic(S), ". Newport")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ st)
p3
```

Plot abx distribution within Typhimurium

```{r, include = FALSE}

# Drop NA
d1 <- typabx %>% drop_na()

# Get the number distinct STs

a <- d1 %>% select(id, st) %>% group_by(id)
b <- distinct(a, id, st)
table(b$st)

###############################################
# Calculations for Other STs 

d2a <- d1 %>% filter(st == "Other STs")

d3a <- d2a %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4a <- d3a %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 1430) %>%
         mutate(prop = (value/total)*100)

d5a <- d4a %>% mutate(st = "Other STs")

###############################################
# Calculations for ST19

d2b <- d1 %>% filter(st == "ST19")

d3b <- d2b %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4b <- d3b %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 12477) %>%
         mutate(prop = (value/total)*100)

d5b <- d4b %>% mutate(st = "ST19")

###############################################
# Calculations for ST313

d2c <- d1 %>% filter(st == "ST313")

d3c <- d2c %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4c <- d3c %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 1493) %>%
         mutate(prop = (value/total)*100)

d5c <- d4c %>% mutate(st = "ST313")

###############################################
# Calculations for ST34

d2d <- d1 %>% filter(st == "ST34")

d3d <- d2d %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4d <- d3d %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 5274) %>%
         mutate(prop = (value/total)*100)

d5d <- d4d %>% mutate(st = "ST34")

#################################################

# Calculations for ST34

d2e <- d1 %>% filter(st == "ST36")

d3e <- d2e %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4e <- d3e %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 835) %>%
         mutate(prop = (value/total)*100)

d5e <- d4e %>% mutate(st = "ST36")

# combined datasets

d6 <- rbind(d5a, d5b, d5c, d5d, d5e)

d7 <- d6 %>% filter(prop >= 25)
p4 <- ggplot(data = d7, mapping = aes(x = prop, y=gene, fill = gene)) + 
      geom_bar(stat = "identity") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      #xlim(0, 110) +
       theme(legend.position = "none") +
      scale_fill_manual(values = c("deeppink3", "bisque", "orange", "purple", "deepskyblue4",
                                   "deeppink4", "darkgreen", "black", "blue", "darkseagreen"))+
      theme(axis.text.y = element_text(size = 25)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle(expression(bold(paste("D.      ", bolditalic(S), ". Typhimurium")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ st)
p4
```
