---
title: "Campylobacter jejuni"
author: "Joao Carlos Gomes-Neto"
date: "7/16/2020"
output: html_document
---

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)    
library(factoextra) 
library(dendextend)
```

MLST and abx data plot C. Jejuni

```{r, include = FALSE}

mlst2 <- read_csv('~/Documents/natasha_papers/prokevo/mlst_output.csv')

mlst2$id <- sapply(strsplit(as.character(mlst2$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst2 %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

data1 <- s1 %>% select(ST) %>%
          drop_na(ST) %>%
          group_by(ST) %>%
          summarize(n = n()) %>%
          arrange(desc(n)) %>%
          mutate(prop = n/sum(n)*100) %>%
          arrange(desc(prop))

data2 <- data1 %>% filter(prop > 1)

p1 <- ggplot(data = data2, mapping = aes(x = reorder(ST, prop), prop)) + 
      geom_bar(stat = "identity", fill="steelblue") + 
      coord_flip() +
      ylim(0, 10) +
      theme_bw() + 
      theme(legend.position = "none") +
      ylab("Proportion") +
      xlab("ST") +
      theme(axis.text.y = element_text(size = 30)) +
      theme(axis.title.y = element_text(size = 40, face = "bold")) +
      theme(axis.title.x = element_text(size = 35, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 25)) +
      ggtitle(expression(bold(paste("A.     ", bolditalic(C), ". jejuni")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      annotate(geom = "text", label = "Filter = proportion > 1%", x = 7.5, y = 7, 
                                  color = "black", size = 15)
p1

# List of selected STs

list_of_st <- data2$ST

####################################################################

# Read in abx data

abx1 <- read_csv('~/Documents/natasha_papers/prokevo/original_resfinder_files/campylobacter_jejuni/sabricate_resfinder_output_jejuni.csv')
abx1$id2 <- sapply(strsplit(as.character(abx1$'#FILE'),'/'), "[", 8)
abx2 <- abx1 %>% separate(id2, c("id", "day"), sep = "\\_")
abx2 <- abx2 %>% mutate(gene = GENE)
abx3 <- abx2 %>% select(id, gene)

# Merge data 

data3 <- left_join(s1, abx3, on = "id")
d1 <- data3
d1 <- d1 %>% drop_na()
###############################################
# Calculations for ST8

d2a <- d1 %>% filter(ST == "8")

d3a <- d2a %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4a <- d3a %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 886) %>%
         mutate(prop = (value/total)*100)

d5a <- d4a %>% mutate(ST = "8")

###############################################
# Calculations for ST45

d2b <- d1 %>% filter(ST == "45")

d3b <- d2b %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4b <- d3b %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 1041) %>%
         mutate(prop = (value/total)*100)

d5b <- d4b %>% mutate(ST = "45")

###############################################
# Calculations for ST48

d2c <- d1 %>% filter(ST == "48")

d3c <- d2c %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4c <- d3c %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 940) %>%
         mutate(prop = (value/total)*100)

d5c <- d4c %>% mutate(ST = "48")

###############################################
# Calculations for ST50

d2d <- d1 %>% filter(ST == "50")

d3d <- d2d %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4d <- d3d %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 932) %>%
         mutate(prop = (value/total)*100)

d5d <- d4d %>% mutate(ST = "50")

#################################################

# Calculations for ST353

d2e <- d1 %>% filter(ST == "353")

d3e <- d2e %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4e <- d3e %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 1108) %>%
         mutate(prop = (value/total)*100)

d5e <- d4e %>% mutate(ST = "353")

#################################################

# Calculations for ST459

d2f <- d1 %>% filter(ST == "459")

d3f <- d2f %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4f <- d3f %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 577) %>%
         mutate(prop = (value/total)*100)

d5f <- d4f %>% mutate(ST = "459")

#################################################

# Calculations for ST806

d2g <- d1 %>% filter(ST == "806")

d3g <- d2g %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4g <- d3g %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 651) %>%
         mutate(prop = (value/total)*100)

d5g <- d4g %>% mutate(ST = "806")

#################################################

# Calculations for ST982

d2h <- d1 %>% filter(ST == "982")

d3h <- d2h %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4h <- d3h %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 940) %>%
         mutate(prop = (value/total)*100)

d5h <- d4h %>% mutate(ST = "982")

# combined datasets

d6 <- rbind(d5a, d5b, d5c, d5d, d5e, d5f, d5g, d5h)

d7 <- d6 %>% filter(prop >= 25)
p2 <- ggplot(data = d7, mapping = aes(x = prop, y=gene, fill = gene)) + 
      geom_bar(stat = "identity") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
       theme(legend.position = "none") +
        scale_fill_brewer(palette = "Set1") +
      theme(axis.text.y = element_text(size = 25)) +
      theme(axis.title.y = element_text(size = 35, face = "bold")) +
      theme(axis.title.x = element_text(size = 30, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 20)) +
      ggtitle(expression(bold(paste("C.     ", bolditalic(C), ". jejuni")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 30, colour = "black", angle = 0)) +
      facet_wrap(~ ST)
p2
```

MLST and abx data plot S. aureus 

```{r, include = FALSE}

data1 <- read_csv('~/Documents/natasha_papers/prokevo/saureusmlst.csv')

# Generate the id column 
data1$id2 <- sapply(strsplit(as.character(data1$FILE),'/'), "[", 8)
data1 <- data1 %>% separate(id2, c("id", "day"), sep = "\\.")


# Select columns of interest

s1 <- data1 %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

data2 <- s1 %>% select(ST) %>%
          drop_na(ST) %>%
          group_by(ST) %>%
          summarize(n = n()) %>%
          arrange(desc(n)) %>%
          mutate(prop = n/sum(n)*100) %>%
          arrange(desc(prop))

data3 <- data2 %>% filter(prop > 1)

p1 <- ggplot(data = data3, mapping = aes(x = reorder(ST, prop), prop)) + 
      geom_bar(stat = "identity", fill="steelblue") + 
      coord_flip() +
      ylim(0, 50) +
      theme_bw() + 
      theme(legend.position = "none") +
      ylab("Proportion") +
      xlab("ST") +
      theme(axis.text.y = element_text(size = 30)) +
      theme(axis.title.y = element_text(size = 40, face = "bold")) +
      theme(axis.title.x = element_text(size = 35, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 25)) +
      ggtitle(expression(bold(paste("B.     ", bolditalic(S), ". aureus")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      annotate(geom = "text", label = "Filter = proportion > 1%", x = 2.5, y = 30, 
                                  color = "black", size = 15)
p1

# List of selected STs

list_of_st <- data3$ST

####################################################################

# Read in abx data

abx1 <- read_csv('~/Documents/natasha_papers/prokevo/original_resfinder_files/staphylococcus_aureus/sabricate_resfinder_output_aureus.csv')
abx1$id2 <- sapply(strsplit(as.character(abx1$'#FILE'),'/'), "[", 8)
abx2 <- abx1 %>% separate(id2, c("id", "day"), sep = "\\.")
abx2 <- abx2 %>% mutate(gene = GENE)
abx3 <- abx2 %>% select(id, gene)

# Merge data 

data3 <- left_join(s1, abx3, on = "id")
d1 <- data3
d1 <- d1 %>% drop_na()
###############################################
# Calculations for ST8

d2a <- d1 %>% filter(ST == "8")

d3a <- d2a %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4a <- d3a %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 4518) %>%
         mutate(prop = (value/total)*100)

d5a <- d4a %>% mutate(ST = "8")

###############################################
# Calculations for ST5

d2b <- d1 %>% filter(ST == "5")

d3b <- d2b %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4b <- d3b %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 3801) %>%
         mutate(prop = (value/total)*100)

d5b <- d4b %>% mutate(ST = "5")

###############################################
# Calculations for ST105

d2c <- d1 %>% filter(ST == "105")

d3c <- d2c %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4c <- d3c %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 1334) %>%
         mutate(prop = (value/total)*100)

d5c <- d4c %>% mutate(ST = "105")

###############################################
# Calculations for ST398

d2d <- d1 %>% filter(ST == "398")

d3d <- d2d %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4d <- d3d %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 276) %>%
         mutate(prop = (value/total)*100)

d5d <- d4d %>% mutate(ST = "398")

#################################################

# Calculations for ST609

d2e <- d1 %>% filter(ST == "609")

d3e <- d2e %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4e <- d3e %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 211) %>%
         mutate(prop = (value/total)*100)

d5e <- d4e %>% mutate(ST = "609")

#################################################

# Calculations for ST45

d2f <- d1 %>% filter(ST == "45")

d3f <- d2f %>% select(id, gene) %>%
    group_by(id, gene) %>%
    summarize(count = n()) %>%
    filter(count <= 1) 

d4f <- d3f %>% group_by(gene) %>% 
         summarize(value = n()) %>%
         mutate(total = 141) %>%
         mutate(prop = (value/total)*100)

d5f <- d4f %>% mutate(ST = "45")

#################################################
# combined datasets

d6 <- rbind(d5a, d5b, d5c, d5d, d5e, d5f)

d7 <- d6 %>% filter(prop >= 25)
p2 <- ggplot(data = d7, mapping = aes(x = prop, y=gene, fill = gene)) + 
      geom_bar(stat = "identity") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
      theme(legend.position = "none") +
        scale_fill_manual(values = c("red", "black", "darkgreen", "orange", "brown",
                                   "purple", "gray", "steelblue", "salmon", "darkred",
                                   "yellow", "pink", "chocolate", "bisque2", "azure3",
                                   "cyan", "darkcyan", "coral4", "brown3", "cornflowerblue", "beige")) +
      theme(axis.text.y = element_text(size = 15)) +
      theme(axis.title.y = element_text(size = 35, face = "bold")) +
      theme(axis.title.x = element_text(size = 30, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 20)) +
      ggtitle(expression(bold(paste("D.     ", bolditalic(S), ". aureus")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 30, colour = "black", angle = 0)) +
      facet_wrap(~ ST)
p2
```
