---
title: "Salmonella antibiotic resistance"
author: "Joao Carlos Gomes-Neto"
date: "7/18/2020"
output: html_document
---

Load packages

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)    
library(factoextra) 
library(dendextend)

```

Salmonella Typhimurium

```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('~/Documents/salmonella_typhimurium_newport_infantis_PAPER_2020/data/typhimurium/global_input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'/'), "[", 3)
s1 <- mlst %>% separate(id2, c("id", "day"), sep = "\\.")

# Select columns of interest

s2 <- s1 %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

# QC the data

skim(s2)

# st

s2$st <- ifelse(s2$ST == 19, "ST19", 
                   ifelse(s2$ST == 34, "ST34", 
                          ifelse(s2$ST == 36, "ST36",
                                 ifelse(s2$ST == 313, "ST313", "Other STs"))))

# Create data1 

data1 <- s2 


# Enter resfinder data

abx1 <- read_csv('~/Documents/natasha_papers/prokevo/typhimurium_resfinder_output_final.csv')
abx1$serovar <- "Typhimirium"

# merge data

typabx <- left_join(data1, abx1, on =  "id")

# select columns that you need

typabx <- typabx %>% select(id, st, gene, serovar)
```

Salmonella Newport

```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('~/Documents/salmonella_typhimurium_newport_infantis_PAPER_2020/data/newport/input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id2, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                  rename(id = id2)

# st

s1$st <- ifelse(s1$ST == 5, "ST5", 
                   ifelse(s1$ST == 45, "ST45", 
                          ifelse(s1$ST == 118, "ST118", "Other STs")))

data1 <- s1

# Enter resfinder data

abx2 <- read_csv('~/Documents/natasha_papers/prokevo/newport_resfinder_output_final.csv')
abx2$serovar <- "Newport"

# merge data

newabx <- left_join(data1, abx2, on =  "id")

# select columns that you need

newabx <- newabx %>% select(id, st, gene, serovar)
```

Salmonella infantis


```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('~/Documents/salmonella_typhimurium_newport_infantis_PAPER_2020/data/infantis/input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id2, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                  rename(id = id2)

# st

s1$st <- ifelse(s1$ST == 32, "ST32", "Other STs")

data1 <- s1

# Enter resfinder data

abx3 <- read_csv('~/Documents/natasha_papers/prokevo/infantis_resfinder_output_final.csv')
abx3$serovar <- "Infantis"

# merge data

infabx <- left_join(data1, abx3, on =  "id")

# select columns that you need

infabx <- infabx %>% select(id, st, gene, serovar)
```

Combine all three datasets and plot resistance based on Serovar
```{r, include = FALSE}

dataAbx <- rbind(typabx, newabx, infabx)

# Drop NA
d1 <- dataAbx %>% drop_na()

# Select ST and gene only

d2 <- d1 %>% select(serovar, gene) %>%
         group_by(serovar, gene) %>%
         summarize(count = n()) %>%
         mutate(prop = count/sum(count)*100)

d3 <- d2 %>% filter(prop > 1)
p1 <- ggplot(data = d3, mapping = aes(x = prop, y=gene)) + 
      geom_bar(stat = "identity", fill = "darkblue") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
      theme(axis.text.y = element_text(size = 35)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle("A.          Serovars") +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ serovar)
p1
```

Plot abx distribution with Infantis

```{r, include = FALSE}

# Drop NA
d1 <- infabx %>% drop_na()

# Select ST and gene only

d2 <- d1 %>% select(st, gene) %>%
         group_by(st, gene) %>%
         summarize(count = n()) %>%
         mutate(prop = count/sum(count)*100)

d3 <- d2 %>% filter(prop > 1)
p2 <- ggplot(data = d3, mapping = aes(x = prop, y=gene)) + 
      geom_bar(stat = "identity", fill = "darkblue") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
      theme(axis.text.y = element_text(size = 35)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle(expression(bold(paste("B.     ", bolditalic(S), ". Infantis")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ st)
p2
```

Plot abx distribution with Newport

```{r, include = FALSE}

# Drop NA
d1 <- newabx %>% drop_na()

# Select ST and gene only

d2 <- d1 %>% select(st, gene) %>%
         group_by(st, gene) %>%
         summarize(count = n()) %>%
         mutate(prop = count/sum(count)*100)

d3 <- d2 %>% filter(prop > 1)
p3 <- ggplot(data = d3, mapping = aes(x = prop, y=gene)) + 
      geom_bar(stat = "identity", fill = "darkblue") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
      theme(axis.text.y = element_text(size = 20)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle(expression(bold(paste("C.     ", bolditalic(S), ". Newport")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ st)
p3
```

Plot abx distribution with Typhimurium

```{r, include = FALSE}

# Drop NA
d1 <- typabx %>% drop_na()

# Select ST and gene only

d2 <- d1 %>% select(st, gene) %>%
         group_by(st, gene) %>%
         summarize(count = n()) %>%
         mutate(prop = count/sum(count)*100)

d3 <- d2 %>% filter(prop > 1)
p4 <- ggplot(data = d3, mapping = aes(x = prop, y=gene)) + 
      geom_bar(stat = "identity", fill = "darkblue") + 
      theme_bw() + 
      xlab("Proportion") +
      ylab("Antibiotic resistance genes") +
      xlim(0, 100) +
      theme(axis.text.y = element_text(size = 18)) +
      theme(axis.title.y = element_text(size = 45, face = "bold")) +
      theme(axis.title.x = element_text(size = 45, face = "bold")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 35)) +
      ggtitle(expression(bold(paste("D.      ", bolditalic(S), ". Typhimurium")))) +
      theme(plot.title = element_text(size = 60, face = "bold")) +
      theme(strip.text.x = element_text(size = 35, colour = "black", angle = 0)) +
      facet_wrap(~ st)
p4
```


